# Generated by Django 6.0.7 on 2026-08-28 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(blank=True)),
                ('direction', models.CharField(choices=[('source', 'Fonte de dados'), ('destination', 'Destino de dados'), ('bidirectional', 'Bidirecional')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('correlation_id', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('succeeded', 'Concluída'), ('failed', 'Falhou')], default='running', max_length=16)),
                ('contract_version', models.CharField(default='v1', max_length=16)),
                ('modified_since', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_inserted', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_cursor', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationsystem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationStagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('source_name', models.CharField(max_length=255)),
                ('source_modified', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('contract_version', models.CharField(max_length=16)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('imported_by_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationsyncrun')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationsystem')),
            ],
            options={
                'indexes': [models.Index(fields=['system', 'dataset', 'source_modified'], name='integration_system__db556b_idx')],
                'constraints': [models.UniqueConstraint(fields=('system', 'dataset', 'source_name'), name='uniq_staging_source_dataset_name')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('completed_through', models.DateTimeField(blank=True, null=True)),
                ('resume_cursor', models.TextField(blank=True)),
                ('resume_modified_since', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integrationsyncrun')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integrationsystem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system', 'dataset'), name='uniq_checkpoint_system_dataset')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=120)),
                ('source_modified', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationsyncrun')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationsystem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system', 'source_name'), name='uniq_warehouse_system_name')],
            },
        ),
    ]
