# Generated by Django 6.1 on 2026-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngsysCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ongsys', models.CharField(db_index=True, max_length=64, unique=True)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, max_length=32, null=True)),
                ('tipo_cliente', models.CharField(blank=True, max_length=64, null=True)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente / Projeto OngSys',
                'verbose_name_plural': 'Clientes / Projetos OngSys',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='OngsysContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_lancamento', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=255)),
                ('fornecedor_documento', models.CharField(blank=True, max_length=32)),
                ('historico_despesa', models.TextField(blank=True)),
                ('tipo_despesa', models.CharField(blank=True, max_length=120)),
                ('data_emissao', models.DateField(blank=True, db_index=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, db_index=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status_pagamento', models.CharField(blank=True, max_length=64)),
                ('projeto_nome', models.CharField(blank=True, db_index=True, max_length=255)),
                ('subprojeto_nome', models.CharField(blank=True, max_length=255)),
                ('conta_contabil', models.CharField(blank=True, max_length=255)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Pagar OngSys',
                'verbose_name_plural': 'Contas a Pagar OngSys',
                'ordering': ['-data_vencimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OngsysContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_lancamento', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=255)),
                ('cliente_documento', models.CharField(blank=True, max_length=32)),
                ('data_emissao', models.DateField(blank=True, db_index=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, null=True)),
                ('data_recebimento', models.DateField(blank=True, db_index=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('projeto_nome', models.CharField(blank=True, db_index=True, max_length=255)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Receber OngSys',
                'verbose_name_plural': 'Contas a Receber OngSys',
                'ordering': ['-data_vencimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OngsysContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ongsys', models.CharField(db_index=True, max_length=64, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=64)),
                ('tipo_contrato', models.CharField(default='PAGAR', max_length=32)),
                ('nome_contraparte', models.CharField(blank=True, max_length=255)),
                ('documento_contraparte', models.CharField(blank=True, max_length=32)),
                ('nome_contrato', models.CharField(max_length=255)),
                ('descricao_contrato', models.TextField(blank=True)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato OngSys',
                'verbose_name_plural': 'Contratos OngSys',
                'ordering': ['nome_contrato'],
            },
        ),
        migrations.CreateModel(
            name='OngsysFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ongsys', models.CharField(db_index=True, max_length=64, unique=True)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, max_length=32, null=True)),
                ('tipo_fornecedor', models.CharField(blank=True, max_length=64, null=True)),
                ('ativo_inativo', models.CharField(default='A', max_length=8)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor OngSys',
                'verbose_name_plural': 'Fornecedores OngSys',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='OngsysLancamentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data_operacao', models.DateField(blank=True, db_index=True, null=True)),
                ('conta_bancaria', models.CharField(blank=True, max_length=255)),
                ('tipo_operacao', models.CharField(blank=True, max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lançamento Bancário OngSys',
                'verbose_name_plural': 'Lançamentos Bancários OngSys',
                'ordering': ['-data_operacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OngsysProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ongsys', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nome_produto', models.CharField(max_length=255)),
                ('descricao_produto', models.TextField(blank=True)),
                ('status', models.CharField(default='ativo', max_length=32)),
                ('grupo', models.CharField(blank=True, max_length=120, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=64, null=True)),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto OngSys',
                'verbose_name_plural': 'Produtos OngSys',
                'ordering': ['nome_produto'],
            },
        ),
    ]
