# Generated by Django 6.0.7 on 2026-08-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_ongsyscliente_ongsyscontapagar_ongsyscontareceber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngsysEndpointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('endpoint_path', models.CharField(max_length=120)),
                ('metodo', models.CharField(default='GET', max_length=10)),
                ('ultimo_status_http', models.IntegerField(blank=True, null=True)),
                ('status_classificacao', models.CharField(choices=[('success', 'Operacional (HTTP 200)'), ('validated', 'Requer Parâmetros (HTTP 422)'), ('error', 'Com Falha / Erro'), ('untested', 'Não Testado')], default='untested', max_length=32)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('ultima_vez_testado', models.DateTimeField(blank=True, null=True)),
                ('ultima_vez_sucesso', models.DateTimeField(blank=True, null=True)),
                ('detalhes_resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status de Endpoint OngSys',
                'verbose_name_plural': 'Status de Endpoints OngSys',
                'ordering': ['endpoint_id'],
            },
        ),
    ]
