# Generated by Django 6.1 on 2026-09-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_ongsysendpointstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="OngsysNotaProduto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_ongsys", models.CharField(db_index=True, max_length=64, unique=True)),
                ("numero_nfe", models.CharField(blank=True, db_index=True, max_length=64)),
                ("serie", models.CharField(blank=True, max_length=16)),
                ("chave_acesso", models.CharField(blank=True, db_index=True, max_length=44)),
                ("emitente_nome", models.CharField(blank=True, max_length=255)),
                ("emitente_documento", models.CharField(blank=True, db_index=True, max_length=32)),
                ("destinatario_nome", models.CharField(blank=True, max_length=255)),
                ("destinatario_documento", models.CharField(blank=True, db_index=True, max_length=32)),
                ("data_emissao", models.DateField(blank=True, db_index=True, null=True)),
                ("valor_total", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("natureza_operacao", models.CharField(blank=True, max_length=255)),
                ("dados_brutos", models.JSONField(default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nota Fiscal de Produto (NF-e)",
                "verbose_name_plural": "Notas Fiscais de Produto (NF-e)",
                "ordering": ["-data_emissao", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="OngsysNotaServico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_ongsys", models.CharField(db_index=True, max_length=64, unique=True)),
                ("numero_nota", models.CharField(blank=True, db_index=True, max_length=64)),
                ("codigo_verificacao", models.CharField(blank=True, max_length=64)),
                ("prestador_nome", models.CharField(blank=True, max_length=255)),
                ("prestador_documento", models.CharField(blank=True, db_index=True, max_length=32)),
                ("tomador_nome", models.CharField(blank=True, max_length=255)),
                ("tomador_documento", models.CharField(blank=True, db_index=True, max_length=32)),
                ("data_emissao", models.DateField(blank=True, db_index=True, null=True)),
                ("data_competencia", models.DateField(blank=True, null=True)),
                ("valor_servicos", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("valor_liquido", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("discriminacao_servicos", models.TextField(blank=True)),
                ("dados_brutos", models.JSONField(default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nota Fiscal de Serviço (NFS-e)",
                "verbose_name_plural": "Notas Fiscais de Serviço (NFS-e)",
                "ordering": ["-data_emissao", "-criado_em"],
            },
        ),
    ]
