# Generated by Django 6.1 on 2026-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0004_ongsysnotaproduto_ongsysnotaservico"),
    ]

    operations = [
        migrations.CreateModel(
            name="OngsysAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("log_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("usuario_id", models.CharField(blank=True, db_index=True, max_length=32)),
                ("usuario_nome", models.CharField(blank=True, db_index=True, max_length=255)),
                ("origem", models.CharField(blank=True, db_index=True, max_length=120)),
                ("descricao_transacao", models.TextField(blank=True)),
                ("data_evento", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("dados_brutos", models.JSONField(default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Log de Auditoria OngSys",
                "verbose_name_plural": "Logs de Auditoria OngSys",
                "ordering": ["-data_evento", "-log_id"],
                "indexes": [
                    models.Index(fields=["usuario_nome", "data_evento"], name="integration_usuario_acca10_idx"),
                    models.Index(fields=["origem", "data_evento"], name="integration_origem_b7de8a_idx"),
                ],
            },
        ),
    ]
