# Generated by Django 6.1 on 2026-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_ongsy_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_corrida', models.CharField(db_index=True, max_length=128, verbose_name='ID da Corrida')),
                ('plataforma', models.CharField(choices=[('Uber', 'Uber'), ('99', '99')], db_index=True, default='Uber', max_length=16)),
                ('data_solicitacao', models.CharField(blank=True, max_length=32, verbose_name='Data Solicitação')),
                ('hora_solicitacao', models.CharField(blank=True, max_length=32, verbose_name='Hora Solicitação')),
                ('data_chegada', models.CharField(blank=True, max_length=32, verbose_name='Data Chegada')),
                ('hora_chegada', models.CharField(blank=True, max_length=32, verbose_name='Hora Chegada')),
                ('solicitado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora Início')),
                ('concluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora Fim')),
                ('servico', models.CharField(blank=True, max_length=120, verbose_name='Serviço')),
                ('programa', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Programa / Projeto')),
                ('grupo', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Grupo / Centro de Custo')),
                ('nome', models.CharField(blank=True, max_length=120, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=120, verbose_name='Sobrenome')),
                ('nome_completo', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Nome Completo')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Email')),
                ('detalhamento_despesa', models.TextField(blank=True, verbose_name='Detalhamento da despesa')),
                ('valor_total', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância (km)')),
                ('duracao_minutos', models.IntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('endereco_partida', models.TextField(blank=True, verbose_name='Endereço Partida')),
                ('endereco_destino', models.TextField(blank=True, verbose_name='Endereço Destino')),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Cidade')),
                ('pais', models.CharField(default='Brasil', max_length=64, verbose_name='País')),
                ('status', models.CharField(db_index=True, default='Concluída', max_length=64, verbose_name='Status')),
                ('arquivo_origem', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Arquivo de Origem')),
                ('dados_brutos', models.JSONField(blank=True, default=dict, verbose_name='Dados Brutos JSON')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corrida de Transporte (Uber/99)',
                'verbose_name_plural': 'Corridas de Transporte (Uber/99)',
                'ordering': ['-solicitado_em', '-id'],
                'indexes': [models.Index(fields=['plataforma', 'solicitado_em'], name='integration_platafo_2369e7_idx'), models.Index(fields=['programa', 'solicitado_em'], name='integration_program_3fa91c_idx'), models.Index(fields=['grupo', 'solicitado_em'], name='integration_grupo_027c2e_idx'), models.Index(fields=['nome_completo', 'solicitado_em'], name='integration_nome_co_d2327e_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_corrida', 'plataforma'), name='uniq_transporte_corrida_plataforma')],
            },
        ),
    ]
