# Generated by Django 6.0.7 on 2026-08-03 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_grupo', models.EmailField(max_length=255, unique=True, verbose_name='E-mail do Grupo')),
                ('nome_grupo', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Grupo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo do Workspace',
                'verbose_name_plural': 'Grupos do Workspace',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDataOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail Institucional')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('setor_atual', models.CharField(default='Não Definido', max_length=100, verbose_name='Setor Atual')),
                ('cota_total_gb', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Cota Total (GB)')),
                ('cota_used_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Cota Usada (GB)')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso'), ('Inativo', 'Inativo'), ('Voluntário', 'Voluntário'), ('Alias', 'Apelido / Alias')], default='Ativo', max_length=50, verbose_name='Status da Conta')),
                ('mfa_ativo', models.BooleanField(default=False, verbose_name='MFA/2FA Ativo')),
                ('e_voluntario', models.BooleanField(default=False, verbose_name='É Voluntário')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração do Contrato')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário do Workspace',
                'verbose_name_plural': 'Usuários do Workspace',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso (44 dígitos)')),
                ('numero_nota', models.CharField(max_length=20, verbose_name='Número da Nota Fiscal')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('projeto_vinculado', models.CharField(max_length=100, verbose_name='Projeto Vinculado')),
                ('status_conciliacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Conciliado', 'Conciliado'), ('Inconsistente', 'Inconsistente')], default='Pendente', max_length=50, verbose_name='Status')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataops.usuariodataops')),
            ],
            options={
                'verbose_name': 'Nota Fiscal Conciliada',
                'verbose_name_plural': 'Notas Fiscais & Convênios',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('WARN', 'Alerta / Advertência'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro / Inconsistência')], default='INFO', max_length=10, verbose_name='Nível')),
                ('acao_executada', models.CharField(max_length=100, verbose_name='Ação Executada')),
                ('alvo_impactado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alvo Impactado')),
                ('detalhes', models.TextField(verbose_name='Detalhes da Operação')),
                ('ip_origem', models.CharField(default='127.0.0.1', max_length=45, verbose_name='IP de Origem')),
                ('executado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataops.usuariodataops', verbose_name='Executor')),
            ],
            options={
                'verbose_name': 'Log de Auditoria DataOps',
                'verbose_name_plural': 'Logs de Auditoria DataOps',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculado_em', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='dataops.grupoworkspace')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_vinculados', to='dataops.usuariodataops')),
            ],
            options={
                'verbose_name': 'Membro de Grupo',
                'verbose_name_plural': 'Membros dos Grupos',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
    ]
