# Generated by Django 6.0.7 on 2026-08-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Estrutura / Setor')),
                ('tipo', models.CharField(choices=[('sede', 'Setor da Sede'), ('projeto', 'Projeto de Proteção à Vida')], default='sede', max_length=20, verbose_name='Ramo da Arquitetura')),
                ('pcs_sede', models.IntegerField(default=1, verbose_name='Computadores da Sede')),
                ('dispositivos_moveis', models.IntegerField(default=0, verbose_name='Celulares & Notebooks Externa')),
                ('status', models.CharField(choices=[('Online', 'Ligado (Online)'), ('Offline', 'Desligado (Offline)')], default='Online', max_length=20, verbose_name='Status da Conexão')),
                ('ip_faixa', models.CharField(default='10.8.x.x', max_length=50, verbose_name='Faixa de IP')),
                ('latencia', models.CharField(default='12ms', max_length=20, verbose_name='Latência Média')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estrutura de VPN',
                'verbose_name_plural': 'Estruturas de VPN',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
