# Generated by Django 6.0.7 on 2026-08-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0002_estruturavpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(max_length=200, verbose_name='Nome do Sistema')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla / Código')),
                ('responsavel_nome', models.CharField(max_length=150, verbose_name='Responsável Técnico')),
                ('responsavel_email', models.EmailField(max_length=255, verbose_name='E-mail do Responsável')),
                ('setor_projeto', models.CharField(max_length=100, verbose_name='Setor ou Projeto Vinculado')),
                ('url_acesso', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Acesso / IP')),
                ('tecnologias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stack / Tecnologias')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Sistema')),
                ('criticidade', models.CharField(choices=[('Alta', 'Alta - Crítico'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=20, verbose_name='Criticidade')),
                ('status', models.CharField(choices=[('Operacional', 'Operacional / Em Produção'), ('Desenvolvimento', 'Em Desenvolvimento'), ('Legado', 'Sistema Legado'), ('Descontinuado', 'Descontinuado')], default='Operacional', max_length=30, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Sistema',
                'verbose_name_plural': 'Cadastro dos Sistemas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_formulario', models.CharField(choices=[('cadastro_sistema', 'Cadastro de Sistema'), ('avaliacao_servicos', 'Avaliação de Serviços & TI'), ('suporte_ti', 'Chamado de Suporte TI'), ('voluntario', 'Admissão de Voluntário'), ('termo_lgpd', 'Termo de Aceite LGPD')], max_length=50, verbose_name='Tipo de Formulário')),
                ('nome_respondente', models.CharField(max_length=150, verbose_name='Nome do Respondente')),
                ('email_respondente', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('setor_ou_projeto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor / Projeto')),
                ('avaliacao_nota', models.IntegerField(default=5, verbose_name='Nota de Satisfação (1-5)')),
                ('assunto_ou_categoria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Assunto / Categoria')),
                ('mensagem_detalhes', models.TextField(verbose_name='Mensagem / Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta de Formulário',
                'verbose_name_plural': 'Respostas de Formulários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
