# CDC Core — Inventário de Servidores (Produção)

[production_vps]
vps-cdc-core ansible_host=76.13.227.135 ansible_user=root domain=core.cdc.org.br

[cdc_infrastructure:children]
production_vps

[all:vars]
ansible_python_interpreter=/usr/bin/python3
organization_name="Centro Dom Helder Camara"
